card {
  name: "Strike"
  upgrade_level: 0
  effects: {
    energy_adjust {
      value: -1
    }
  }
  effects: {
    apply_damage {
      value: 6
      target: CHOSEN
    }
  }
}

card {
  name: "Defend"
  upgrade_level: 0
  effects: {
    energy_adjust {
      value: -1
    }
  }
  effects: {
    apply_block {
      value: 5
    }
  }
}

card {
  name: "Bash"
  upgrade_level: 0
  effects: {
    energy_adjust {
      value: -2
    }
  }
  effects: {
    apply_damage {
      value: 5
    }
  }
  effects: {
    apply_status {
      status: VULNERABLE
      value: 2
      target: CHOSEN
    }
  }
}
